<myLayout>:
    canvas.before:
        Color:
            rgba: 0.17, 0.17, 0.18, 1
        Rectangle:
            pos: self.pos
            size: self.size

    Label:
        text: "Teva (Build 5.14.24)"
        font_size: root.font_size  # Bind the font size to the dynamic property
        color: 1, 1, 1, 1
        size_hint: None, None
        size: self.texture_size
        pos_hint: {'center_x': 0.5, 'center_y': 0.95}